#!/bin/bash
# Simple key value database
import misc/default
default ADB_ROOT="$HOME/kona/adb"
mkdir -p "$ADB_ROOT"
ADB_SELF=ADB
ADB_FILE=0

# Creates a new database object
function adb_new {

}

# Selects records matching, all
function adb_get {
	
}

# Selects records, only less
function adb_less {

}

# Selects records, only more
function adb_more {
	
}

# Adds a new record
function adb_add {
	# TODO: Use file handles
	printf "\\30%s" "$1" >> "$ADB_ROOT/$ADB_FILE" ||
		return 1
	shift
	while [[ $# -gt 0 ]] ; do
		printf "\\31%s" "$1" >> "$ADB_ROOT/$ADB_FILE" ||
			return 1
		shift
	done
}

# Deletes a record
function adb_delete {

}

# Formates output
function adb_format {

}


